accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView,LogoutView
app_name='accounts'

urlpatterns=[
    url(r'^$',views.IndexView.as_view(),name='homepage'),
    url(r'^signup/',views.signup,name='signup'),
    url(r'^login/',LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'^logout/',LogoutView.as_view(),name='logout'),
    url(r'^landing/',views.LandingPageView.as_view(),name='landing'),
    url(r'^createitem/',views.itemCreateView,name='item_create'),
    url(r'^listitem/',views.ItemListView.as_view(),name='itemlist'),
    url(r'^item/(?P<pk>\d+)/',views.ItemDetailView.as_view(),name='item_detail')


]

discussion_forum/urls.py
from django.conf.urls import url
from discussion_forum import views
app_name='discussion_forum'

urlpatterns=[
    url(r'^$',views.ThreadListView.as_view(),name='discussion_homepage'),
    url(r'^create_thread/$',views.create_thread,name='create_thread'),
    url(r'^thread/(?P<pk>\d+)/$',views.ThreadDetailView.as_view(),name='thread_detail'),
    url(r'^thread/(?P<pk>\d+)/create_comment/$',views.create_comment,name='create_comment'),
]

exchange2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
# from django.contrib.auth.views import LoginView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',TemplateView.as_view(template_name='index.html'),name='index'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^discussion/',include('discussion_forum.urls')),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Details(models.Model):
    user=models.OneToOneField(User,related_name='details')
    branch=models.CharField(max_length=264)
    semester=models.CharField(max_length=264)

    def __str__(self):
        return self.user.username


class Items(models.Model):
    user=models.ForeignKey(User,related_name='items')
    name=models.CharField(max_length=263)
    category=models.CharField(max_length=253)

    def __str__(self):
        return self.name

discussion_forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Thread(models.Model):
    name=models.CharField(max_length=264)
    description=models.TextField()
    user=models.ForeignKey(User,related_name='threads')
    created_time=models.DateTimeField(default=timezone.now())
    approved_time=models.DateTimeField(blank=True,null=True)
    approved_thread=models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def approve_thread(self):
        self.approved_time=timezone.now()
        self.approve_thread=True
        self.save()

class Comments(models.Model):
    thread=models.ForeignKey(Thread,related_name='comments')
    comment=models.TextField()
    created_time=models.DateTimeField(default=timezone.now())
    approved_time=models.DateTimeField(blank=True,null=True)
    approved_comment=models.BooleanField(default=False)

    def __str__(self):
        return self.comment

    def approve_comment(self):
        self.approved_time=timezone.now()
        self.approved_comment=True

accounts/forms.py
from django import forms
from accounts.models import Details,Items
class Detailsform(forms.ModelForm):

    class Meta():
        model=Details
        fields=('branch','semester')

class ItemCreateForm(forms.ModelForm):

    class Meta():
        model=Items
        fields=('name','category')

discussion_forum/forms.py
from django import forms
from discussion_forum.models import Comments,Thread
class ThreadForm(forms.ModelForm):

    class Meta():
        model=Thread
        fields=('name','description')

class CommentForm(forms.ModelForm):

    class Meta():
        model=Comments
        fields=('comment',)

accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView,DetailView
from django.contrib.auth.forms import UserCreationForm
from accounts.forms import Detailsform,ItemCreateForm
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from accounts.models import Items
# Create your views here.


class IndexView(TemplateView):
    template_name='accounts/account_index.html'

class LandingPageView(TemplateView):
    template_name='accounts/landingpage.html'

class ItemListView(LoginRequiredMixin,ListView):
    login_url='/accounts/login'
    redirect_field_name='accounts/items_list.html'
    model=Items
    context_object_name='items'

    def get_queryset(self):
        return Items.objects.all().order_by('name')

class ItemDetailView(DetailView):
    model=Items
@login_required
def itemCreateView(request):
    if request.method=='POST':
        itemform=ItemCreateForm(request.POST)
        if itemform.is_valid():
            item=itemform.save(commit=False)
            item.user=request.user
            item.save()
            return redirect('accounts:itemlist')
    else:
        itemform=ItemCreateForm()
    return render(request,'accounts/item_createpage.html',context={'itemform':itemform})

def signup(request):
    if request.method == 'POST':
        userform=UserCreationForm(request.POST)
        detailform=Detailsform(request.POST)
        if userform.is_valid() and detailform.is_valid():
            user=userform.save()
            user.save()
            detail=detailform.save(commit=False)
            detail.user=user
            detail.save()
            return redirect('accounts:login')
    else:
        userform=UserCreationForm()
        detailform=Detailsform()
    return render(request,'accounts/signup.html',context={'userform':userform,
                                                            'detailform':detailform})

discussion_forum/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import TemplateView,ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from discussion_forum.forms import CommentForm,ThreadForm
from discussion_forum.models import Comments,Thread

# Create your views here.


class ThreadListView(LoginRequiredMixin,ListView):
    template_name='discussion_forum/discussion_index.html'
    login_url='/accounts/login'
    redirect_field_name='discussion_forum/discussion_index.html'
    model=Thread
    context_object_name='threads'
class ThreadDetailView(LoginRequiredMixin,DetailView):
    model=Thread

@login_required
def create_thread(request):
    if request.method=='POST':
        threadform=ThreadForm(request.POST)
        if threadform.is_valid():
            thread=threadform.save(commit=False)
            thread.user=request.user
            thread.save()
            return redirect('discussion_forum:discussion_homepage')
    else:
        threadform=ThreadForm()
    return render(request,'discussion_forum/create_thread.html',context={'threadform':threadform})

@login_required
def create_comment(request,pk):
    thread=get_object_or_404(Thread,pk=pk)
    if request.method=='POST':
        commentform=CommentForm(request.POST)
        if commentform.is_valid():
            comment=commentform.save(commit=False)
            comment.thread=thread
            comment.save()
            return redirect('discussion_forum:thread_detail',pk=thread.pk)
    else:
        commentform=CommentForm()
    return render(request,'discussion_forum/create_comment.html',context={'commentform':commentform})

accounts/templates/accounts/account_index.html
{% extends "base.html" %}

{% block content%}
this is the account index page
{% endblock%}

accounts/templates/accounts/item_createpage.html
{% extends "base.html" %}
{% load bootstrap3%}
{% block content%}
  <form class="" action="{% url 'accounts:item_create'%}" method="post">
    {% csrf_token%}
    {%bootstrap_form itemform%}
    <input type="submit" name="" value="Createitem">
  </form>
{% endblock%}

accounts/templates/accounts/items_detail.html
{% extends "base.html" %}
{% load bootstrap3%}
{% block content%}
  <div class="jumbotron">
    <h2>{{items.name}}</h2>
    <h5>Item Catogory:{{items.category}}</h5>
    <h5>Posted by :{{items.user.username}}</h5>
    <h5>branch: {{items.user.details.branch}}</h5>
    <h5>semester: {{items.user.details.semester}}</h5>
  </div>
{% endblock%}

accounts/templates/accounts/items_list.html
{% extends "base.html" %}
{%load bootstrap3%}
{% block content%}
<br><br><br>
  {% for item in items%}
    <div class="container">
      <a href="{% url 'accounts:item_detail' pk=item.pk%}">
        <div class="jumbotron">
          <h3>{{item.name}}</h3>
          <h5>Posted by:{{item.user.username}}</h5>
        </div>
      </a>
    </div>
  {% endfor%}

  <div class="">
    <a href="{% url 'accounts:item_create'%}" class="btn btn-lg btn-primary">Add Item</a>
  </div>
  <br><br>
{% endblock%}

accounts/templates/accounts/landingpage.html
{% extends "base.html" %}
{%load bootstrap3%}
{% block content%}
  <div class="">
    This is the landing homepage
    lets ROKC
    {{user.username}}
  </div>
{% endblock%}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{%load bootstrap3%}
{% block content%}
  <form class="" action="{% url 'accounts:login'%}" method="post">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit" name="" value="login">
  </form>
{% endblock%}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{%load bootstrap3%}
{% block content%}
  <h1>Signup Here!</h1>
  <form class="" action="{% url 'accounts:signup'%}" method="post">
    {% csrf_token%}
    {% bootstrap_form userform%}
    {% bootstrap_form detailform%}
    <input type="submit" name="" value="signup">
  </form>
{% endblock%}

discussion_forum/templates/discussion_forum/create_comment.html
{% extends 'base.html'%}
{% load bootstrap3%}
{% block content%}
  <div class="container">
    <form class="" action="" method="post">
      {% csrf_token%}
      {% bootstrap_form commentform%}
      <input type="submit" class="btn btn-primary" name="" value="Submit">
    </form>
  </div>
{% endblock%}

discussion_forum/templates/discussion_forum/create_thread.html
{% extends 'base.html'%}
{% load bootstrap3%}
{% block content%}
<div class="container">
  <form class="" action="{% url 'discussion_forum:create_thread'%}" method="post">
    {% csrf_token%}
    {% bootstrap_form threadform%}
    <input type="submit" name="" value="submit">
  </form>
</div>
{% endblock%}

discussion_forum/templates/discussion_forum/discussion_index.html
{% extends 'base.html'%}
{% block content%}
<div class="container thread_heading centered">
  <h2>Here goes the Discussion in RIT. Be a part of the discussion</h2>
</div>
<br>
{% for thread in threads %}
  {% if thread.approved_thread %}
  <a href="{% url 'discussion_forum:thread_detail' pk=thread.pk%}">
    <div class="container hover_shadow">
      <div class="col-sm-4">
        <h1>{{thread.name}}</h1>
      </div>
      <div class="thread_description_div col-sm-8">
        <h3 class="">{{thread.description}}</h3>
      </div>
      <div class="col-sm-12">
        Created By : {{thread.user.username}} &nbspOn : {{thread.created_time}},
        <p>Comments : {{thread.comments.count}}</p>
      </div>
    </div>
  </a>
  <hr>
  {% endif%}
{% endfor%}
<div class="container">
  <a href="{% url 'discussion_forum:create_thread'%}" class="btn btn-primary col-sm-12">Create New Thread</a>
</div>
{% endblock%}

discussion_forum/templates/discussion_forum/thread_detail.html
{% extends 'base.html'%}
{% load bootstrap3%}
{% block content%}
  <div class="container thread_description_div thread_heading">
    <h3>Thread Name:{{thread.name}}</h3>
    <h4>Description:{{thread.description}}</h4>
    {{thread.comments.count}}Comment
  </div>
  <br>
  {% if thread.comments.count == 0%}
    <h3>No Comments Yet!</h3>
  {% else%}
  {% for comment in thread.comments.all%}
    <div class="container">
      <p>{{comment.comment}}</p>
      By:{{comment.thread.user.username}}
      <p>Commented On: {{comment.created_time}}</p>
      {% if comment.thread.user.username == user.username%}
        <a href="#" class="btn btn-primary">{{comment.thread.user.username}}</a>
      {% endif%}
    </div>
    <hr>
  {% endfor%}
  {% endif%}

    <a href="{% url 'discussion_forum:create_comment' pk=thread.pk%}" class="btn btn-primary col-sm-12">Add Comment</a>

{% endblock%}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet"
         href="https://fonts.googleapis.com/css?family=Montserrat">

    <link rel="stylesheet" href="{% static 'css/base.css'%}">
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    <link rel="stylesheet" href="{% static 'css/thread.css'%}">

  </head>
  <body>
    <nav class="col-sm-12 flex navbar mynav navbar-inverse navbar-static-top" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'index'%}">Exchange</a>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated%}
            <li><a href="#">About</a></li>
            <li><a href="#">Groups</a></li>
            <li><a href="#">{{user.username}}</a></li>
            <li><a href="{% url 'accounts:logout'%}">Logout</a></li>
          {% else%}
            <li><a href="#">Groups</a></li>
            <li><a href="{% url 'accounts:login'%}">Login</a></li>
            <li><a href="{% url 'accounts:signup'%}">Signup</a></li>

          {% endif%}
        </ul>
      </div>
    </nav>
      {% block content%}

      {% endblock%}
  </body>
</html>

templates/index.html
{% extends 'base.html'%}
{% load staticfiles%}

{% block content %}
  <div class="img1">
    <div class="col-sm-4 discussion_image">

    </div>
    <div class="col-sm-8 discussion_content">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
    <div class="col-sm-12 discussion_button_div">
      <a href="{% url 'discussion_forum:discussion_homepage'%}" class="btn btn-primary" id="discussion_button">Take me to discussion</a>
    </div>
  </div>

  <div class="img2">
    <div class="col-sm-8 exchange_content discussion_content">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
    <div class="col-sm-4 exchange_image discussion_image">

    </div>
    <div class="col-sm-12 exchange_button_div discussion_button_div">
      <a href="{% url 'accounts:itemlist'%}" class="btn btn-primary" id="discussion_button">Take me to Exchange</a>
    </div>
  </div>
{% endblock%}